Feature: Document/Result Schema 모델 작성
Figci/Figci-Server pull request #10
Opened 2024-02-02 17:52 UTC by doitchuu

## Fix (이슈 번호)
closes #8

<br />

## 해결하려던 문제를 알려주세요!
초기 백엔드 사전 세팅으로 MongoDB의 데이터 구조와 무결성을 엄격하게 관리하기 위해 
스키마를 활용해 데이터 구조를 정의하려 했습니다.

<br />

## 어떻게 해결했나요?
Document Schema 내에서는 Document,  Result 스키마로 크게 나누고, 
`Document` 스키마 내부에는 PageSchema, FrameSchema, NodeSchema 순으로 임베디드되어 각각 중첩되어 있습니다.
Result 스키마 내부에는 DifferenceSchema가 임베디드 형식으로 중첩되어 있고, Result에서 `FrameSchema`를 

`FrameSchema`가 `DocumentSchema` 내의 `PageSchema` 안에 중첩되어 있는 상황을 고려하여
`pre` 함수를 만들어 중첩되어 있는 `FrameSchema`를 가져올 수 있도록 설정해두었습니다.

<br />

## 우려사항이 있나요?(선택사항)
1차 스키마 디자인에서는 관계형 스키마 디자인과 `Document` > `Page `> `Node`와
`Result` > `Frame` > `Difference`를 관계형으로 짰다면,
현재 스키마 디자인은 `Document`, `Result` 스키마 디자인으로 크게 나뉘어 있습니다.

Page, Frame, Node 스키마 디자인의 경우 Document 하위 카테고리로 개별로 사용되는 스키마가 아니기 때문에 
임베디드 형식으로 각각 상위의 스키마 내부에 종속되는 형태로 디자인되어 있고, MongoDB의 경우 관계형 데이터 구조를 
최대한 지양하고 있습니다.(관련 문서는 바로 정리해서 올리겠습니다.)

저희가 걱정한 임베디드 형식으로 할 경우 우려했던 성능과 용량 문제는 
기능 구현 후 하단 링크로 girdfs 방식이나 bson-documents 방식을 차용해 해결해봐도 좋을 것 같습니다.

![2차 스키마](https://github.com/Figci/Figci-Server/assets/43771772/cc466657-10e2-426f-9537-b2aed9abe81b)

https://www.mongodb.com/docs/manual/reference/limits/#bson-documents
https://www.mongodb.com/docs/manual/core/gridfs/
<br />

## 잠깐! 확인해보셨나요?

- [X]  셀프 리뷰는 완료하셨나요?
- [X]  가장 최신 브랜치를 pull했나요?
- [X]  base 브랜치명을 확인하셨나요? (Front, Backend, feature 등)
- [X]  코드 컨벤션을 모두 지켰나요?
- [X]  적절한 라벨이 있나요?
- [X]  assignee가 있나요?

<br />

## Attachment

### 초기 스키마 디자인(2024.01.31)
![1차 스키마](https://github.com/Figci/Figci-Server/assets/43771772/d216c103-877c-4d7f-9429-aff42a8deb34)
<br />

2024-02-02 18:03 UTC, kyeongjun-ko commented on src/models/Document.js
> +  nodeId: { type: String, require: true, unique: true },
P3: `NodeSchema`  에서는 다른 페이지 비교시 공통된 노드 `id`를 가진 노드가 저장될수 없다.
`unique` 속성은 기존 true => 변경후 false 로 설정 해야 할것 같습니다.

ex) `unique: true` 설정 시 예측 가능한 상황
1. v1 과 v2 버전의 로그인 페이지 비교 후 회원가입 페이지 비교할때
- 회원가입 페이지의 `document` > `canvas` > `children` 첫번째 프레임 노드 Id가  1:3 일때 
- 로그인 페이지의 `document` > `canvas` > `children` 첫번째 프레임 노드 Id가  1:3 일 수있다.

2. v1 과 v3 버전의 로그인 페이지 비교 후 v2 과 v3 버전의 로그인 페이지 비교 시
- v3 로그인 페이지의 `document` > `canvas` > `children` 첫번째 노드 Id가  1:3 일때
- v1 로그인 페이지의 `document` > `canvas` > `children` 첫번째 노드 Id 또한  1:3 일 수 있다.

2024-02-02 18:05 UTC, kyeongjun-ko commented on src/models/Document.js
> +  pageId: { type: String, require: true, unique: true },
P3: `PageSchema` 와 `FrameSchema` 또한 같은 Id를 가진 경우에는 입력시 에러가 발생한다.
상기 언급했던 `unique` 설정을 변경할 필요가 있을것 같습니다.

2024-02-02 18:07 UTC, doitchuu commented on src/models/Document.js
> +  pageId: { type: String, require: true, unique: true },
확인 감사합니다. 같은 id가 입력될 수 있겠네요!
위의 코멘트와 같이 unique 설정 변경해두겠습니다 👍

2024-02-02 18:07 UTC, kyeongjun-ko commented on src/models/Document.js
> +  pages: [PageSchema],
D3: 파일 단 `DocumentSchema` 에서 파일명을 UI에 렌더하기 위해 name 속성을 저장한다면
페이지 단인 `PageSchema` 에서도 페이지 목록을 UI에 렌더하기 위해서 name 속성을 저장해야한다.

2024-02-02 18:10 UTC, kyeongjun-ko commented on src/models/Result.js
> +ResultSchema.pre(/^find/, function (next) {
P5: 몽구스에서 어떤 스키마에 대해서 함수 실행 이벤트를 만들수 있군요 👍 👍

2024-02-02 19:24 UTC, tjd985 requested changes
PR확인 했습니다!
수정 요청사항 확인 부탁드립니다!

2024-02-02 19:24 UTC, tjd985 commented on src/models/Document.js
> +});
- P1
스키마 디자인에는 `NodeSchema`에 `frameId`필드가 존재하는데 로직 작성 시 빠진 것 같습니다!
반영 부탁드립니다!

2024-02-02 19:24 UTC, tjd985 commented on src/models/Result.js
> +});
`pre`미들웨어에서의 `this`가 의미하는것이 잘 이해가 안되서 찾아봤더니
콜백함수를 `함수 선언식`으로 작성하게 되면 호출객체(인스턴스) 를 가리키고
`화살표 함수`로 작성하면 해당 스키마를 가리킨다고 [stack overflow](https://stackoverflow.com/questions/66839427/mongoose-middleware-schema-presave#:~:text=The%20difference%20is,object%20(user%20instance).)에나와있네요!

`populate`를 사용하기 위해서 함수선언식으로 작성해주어서 this가 인스턴스를 가리키게 하신 점이 인상깊습니다.

\+
- P1
`ResultSchema`의 인스턴스로 저장된 페이지의 Frame 서브트리를 갖기 위해서 연속된 populate를 사용하신것으로 생각되는데, 유저가 동일한 페이지를 요청을 할 때 DB에서 유저가 요청한 페이지에 대한 결과가 있는지 확인하려면 `ResultSchema`가 해당 `PageID`를 필드로 갖고있어야 할 것 같습니다!
스키마 디자인에는 반영이 되있는데 빠트리신 것 같네요 😂
수정 부탁드립니다!

2024-02-03 05:15 UTC, doitchuu reviewed
코멘트 확인 부탁드립니다.

2024-02-03 05:15 UTC, doitchuu commented on src/models/Document.js
> +  pages: [PageSchema],
해당 속성은 말씀대로 중복될 수 있어 지워두겠습니다. 감사합니다.

2024-02-03 05:15 UTC, doitchuu commented on src/models/Document.js
> +});
`Node`를 가지고 올 때 Frame 내부에 스키마에 저장되기 때문에 
`Frame`과 같이 데이터를 가져오는 걸로 알고 있는데 데이터를 FrameId를 추가로 넣어야 할 이유가 있을까요?

해당 사안 논의된 후에 스키마 image는 헷갈릴 수 있으니 수정해두겠습니다!

2024-02-03 05:15 UTC, doitchuu commented on src/models/Result.js
> +});
해당 내용은 반영해두겠습니다!

2024-02-03 05:16 UTC, tjd985 reviewed
코멘트 남겼습니다!
확인 부탁드립니다.

2024-02-03 05:16 UTC, tjd985 commented on src/models/Document.js
> +});
말씀 들어보니 필요없는 field인 것 같네요!
설명 감사합니다!

2024-02-03 06:00 UTC, tjd985 approved these changes
확인했습니다!
피드백 반영하시느라 고생하셨습니다!

2024-02-03 06:01 UTC, merged