Feature: 버전 공통 페이지 응답 및 서브트리 DB저장 기능 구현
Figci/Figci-Server pull request #12
Opened 2024-02-04 14:56 UTC by doitchuu

## Fix (이슈 번호)
closes #6

<br />

## 해결하려던 문제를 알려주세요!
사용자가 선택한 버전의 각각의 서브트리를 저장 후 
공통 페이지 리스트를 응답으로 보내야 합니다.

<br />

## 어떻게 해결했나요?
1. **Figma API 연동**: 프로젝트의 버전 데이터를 Figma API를 통해 가져옵니다.
2. **깊이 우선 탐색(DFS) 적용**: 피그마 파일의 JSON 구조를 DFS를 이용해 탐색하며, 
각 Depth와 Type에 따라 데이터를 처리합니다.
3. **데이터베이스 저장 로직 구현**: 탐색된 데이터를 Project 스키마, Page 스키마에 맞게 분류하여 저장합니다. 프레임 이하 단위의 노드들은 Node 스키마에 저장합니다.
4. DB에 해당 결과값이 없다면, Figma API를 Before와 After버전의 서브 트리를 가져와
Before와 After버전의 **서브 트리 평탄화 하여 DB에 저장**했습니다.
5. **두 버전 내 공통 페이지 리스트 구현**: 동일 파일 버전 내 동일한 `pageId`들만 모아 공통 페이지 리스트를 만들어 클라이언트에게 전달하는 로직을 구현했습니다.

<br />

## 우려사항이 있나요?(선택사항)

### 1. 토큰 전달 방식 수정
현재 토큰을 전달하는 방식은 기존에 작성되어 있던 `Figma X Token` 전달 방식을 
사용하고 있습니다. 클라이언트 내 `OAuth 2.0` 로그인 방식 구현 후, 수정이 필요합니다.

### 2. ESLint 함수 선언 순서 에러
![eslint error](https://github.com/Figci/Figci-Server/assets/43771772/29d75c9d-f54a-4274-9916-8445d52f43a4)
lint 검사 시, 함수 선언의 순서에 따라 에러가 발생합니다. 함수선언문이라도 
함수를 실행하기 전에 선언해두어야 합니다. 에러나기 쉬운 케이스라 공유 드립니다!

### 3. MongoDB Skema Design 수정
아래 Attachment에 있는 스키마 디자인 참고 부탁드립니다. 
클라이언트 로직 상 필요한 속성(페이지, 화면 명)을 추가했습니다.

### 4. Controller 내 요청에 따른 응답 로직 작성
`projectController` 내 응답 로직을 따로 분리해두었습니다.

관심사 분리와 가독성 측면에서 분리했는데 예를 들어 현재 저희는 이전, 다음 버전 별 
피그마 파일 데이터를 받아와 공통 페이지를 찾고 전달하는 방식으로 
복잡하고 긴 로직으로 이루어져 있습니다.

그 이유로, `router` 디렉토리 내에서는 Endpoint와 Controller만 연결하는 방식으로 작업했고, 
현 방식이 Approve 되면 동일하게 코드 작성 부탁드립니다.

<br />

## 잠깐! 확인해보셨나요?

- [X]  셀프 리뷰는 완료하셨나요?
- [X]  가장 최신 브랜치를 pull했나요?
- [X]  base 브랜치명을 확인하셨나요? (Front, Backend, feature 등)
- [X]  코드 컨벤션을 모두 지켰나요?
- [X]  적절한 라벨이 있나요?
- [X]  assignee가 있나요?

<br />

## Attachment(선택사항) 

### 3차 스키마 디자인
<img width="692" alt="3차 스키마 디자인" src="https://github.com/Figci/Figci-Server/assets/43771772/acf2ffe8-ad3e-4402-b981-770bca2b0b1b">

`Frame`, `Page`, `Node`의 이름을 명시해주고, 클라이언트에 데이터 전송 시 
각 데이터의 name 정보가 필요해 `name` 속성들을 추가했습니다. 

[이전 스키마 디자인](https://github.com/Figci/Figci-Server/pull/10#issue-2115474545)

<br />

2024-02-04 16:41 UTC, tjd985 reviewed
코멘트 확인 후 피드백 부탁드립니다!

2024-02-04 16:41 UTC, tjd985 commented on src/routers/projects.js
>  });
해당 `endpoint`는 혹시 어떤 기능을 위해서 남겨놓으신건지 궁금합니다!

2024-02-04 16:41 UTC, tjd985 commented on src/controllers/projectController.js
> +    );
```suggestion
const getAllVersions = async (req, res) => {
  const { projectId } = req.params;
  const accessToken = req.headers.authorization;

  try {
    const getVersions = await fetch(
      `https://api.figma.com/v1/files/${projectId}/versions`,
      {
        method: "GET",
        headers: {
          "X-FIGMA-TOKEN": accessToken,
        },
      },
    );
    
    
  
    ...
    
    
  module.exports = { getAllversions, getCommonPages };
```

- **`P2`**
1. 라우터 콜백함수는 arrow function으로 작성되어져 있는데 컨트롤러는 함수선언식으로 작성되어져 있어서
통일 해주면 좋을 것 같은데 혹시 어떻게 생각하시나요!

2. 현재는 함수를 선언할 때 prefix로 `exports.`을 붙혀주고 있는데 각각 함수선언과 `export`문을 분리해서 작성하면
조금 더 깔끔해 질 것 같습니다!
혹시 슬기님 생각은 어떠신가요?

2024-02-04 16:41 UTC, tjd985 commented on src/controllers/projectController.js
> +    }
- **_P3_**
컨트롤러에서 작성된 에러메세지들은 저희가 FigmaAPi를 통해서 version를 받아 올때도 재사용 할 수 있을것 같습니다!
따로 상수들만 모아놓은 디렉토리를 만들어 모듈화를 하여 에러가 발생하였을 때
모듈화 한 객체를 `import`하여 해당 에러 코드에 따라서 메세지를 가져올 수 있다면 좋을 것 같습니다!

2024-02-04 16:41 UTC, tjd985 commented on src/controllers/projectController.js
> +    }
```suggestion
    const beforeDocument =
      await getDocument(projectId, beforeVersion) ||
      await createDocument(projectId, beforeVersion);
      
    const afterDocument =
      await getDocument(projectId, afterVersion) ||
      await createDocument(projectId, afterVersion);
```
- `P2`
`let`을 사용하기보다는 `||`를 이용하면 `const`로 변수를 재할당 하지 않고 사용할 수 있어서
사이드 이펙트가 줄어들것 같은데 어떻게 생각하시나요?

2024-02-04 16:41 UTC, tjd985 commented on src/controllers/projectController.js
> +  }
- `P3`
처음 `document`를 선언 할 때는 figma project의 tree구조를 받고있고
`await Document.create(document)`는 직렬화 된 트리를 return하고있는 것 같습니다!

각각 return하는 값의 의미가 다르고, 성질이 다른데 `document`라는 한개의 변수에 값을 재할당 하기 보다는
각각 `const`로 선언해서
```suggestion
    const document = await saveFigmaDataAsNestedStructure(
      figmaData.document,
      null,
      0,
    );

    document.projectKey = projectKey;
    document.versionId = versionId;

    const flattenedDocument = await Document.create(document);

    return flattenedDocument;
  }
```

이런식으로 작성해도 좋을 것 같습니다!
저는 `let`은 최대한 사용을 지양하는것이 좋다고 생각하기 때문입니다!

2024-02-04 16:41 UTC, tjd985 commented on src/controllers/projectController.js
> +  }
위 코멘트와 동일합니다!

2024-02-04 16:41 UTC, tjd985 commented on src/routers/projects.js
> +router.get("/:projectId/pages", projectController.getCommonPages);
`controller`로 로직을 분리하니 관심사가 분리 된 것이 눈에 딱 보여서 좋은 것 같습니다! 👍🏻

2024-02-04 16:41 UTC, tjd985 commented on src/utils/comparePages.js
> +  const matchedPages = [];
- `P4`
`mathedPageList`라는 변수명은 어떠세요?

2024-02-04 16:41 UTC, tjd985 commented on src/utils/saveFigmaDataAsNestedStructure.js
> +async function saveFigmaDataAsNestedStructure(
변수명을 오래 고민한것 같아서 좋네요! 💯

2024-02-04 16:52 UTC, doitchuu commented on src/utils/comparePages.js
> +  const matchedPages = [];
`List`도 좋네요! 배열을 반환값으로 전달하니 좋은 것 같아요! 👍

2024-02-04 16:54 UTC, doitchuu commented on src/controllers/projectController.js
> +  }
저 또한 `let`를 최대한 지양하고 싶었는데 
제안해주신 방식이 더 좋은 것 같습니다! 

코드 가독성도 높이고 좋네요 👍

2024-02-04 16:55 UTC, doitchuu commented on src/controllers/projectController.js
> +    }
let은 최대한 지양하는 게 성호님 말씀대로 맞는 것 같습니다.
해당 내용도 바로 반영하겠습니다. 감사합니다! 👍

2024-02-04 16:56 UTC, doitchuu commented on src/controllers/projectController.js
> +    }
이 부분 제가 놓친 것 같네요! 에러메세지들은 따로 모듈화해두겠습니다 👍

2024-02-05 01:28 UTC, doitchuu commented on src/routers/projects.js
>  });
해당 endpoint는 사용할 필요가 없을 듯해서 지워두겠습니다 🥲

2024-02-05 02:31 UTC, kyeongjun-ko submitted a review, later dismissed
리뷰 피드백 부탁드립니다.

2024-02-05 02:31 UTC, kyeongjun-ko commented on src/controllers/projectController.js
> +const saveFigmaDataAsNestedStructure = require("../utils/saveFigmaDataAsNestedStructure");
P4: 함수명을 명시적으로 짓되 비슷한 의미의 단어가 중복되지 않는게 좋은것 같습니다.
`structure`는 `data`에 포함되 있는 의미라고 생각해서 `data` 써도 충분히 명시적인것 같은데
`saveNestedFigmaData` 는 어떠실까요

2024-02-05 02:31 UTC, kyeongjun-ko commented on src/controllers/projectController.js
> +exports.getAllVersions = async function (req, res) {
P4: 함수명 앞에 export를 붙여서 export 하셨군요

기존에 사용되던 방식에서 변경한 다른 이유가 있을까요? 
Export 방식이 확정 되면 노션 컨벤션에 추가하면 좋겠네요

```
// 기존 export 방식
function test() {
    return null;
};

default export = test;
```

2024-02-05 02:31 UTC, kyeongjun-ko commented on src/utils/saveFigmaDataAsNestedStructure.js
> +const PAGE_UNIT_DEPTH = 1;
P5: Node와 Unit 모두 비슷한 의미를 가지고 있는것 같은데
저희가 다루고 있는건 Node
PAGE_UNIT_DEPTH 보다 PAGE_NODE_DEPTH 가 더 맞지 않을까요?

2024-02-05 02:31 UTC, kyeongjun-ko commented on src/utils/saveFigmaDataAsNestedStructure.js
> +      "scrollBehavior",
P4: `scrollBehavior`속성은 렌더링에 관여하는 핵심속성은 아니라고 생각했는데
키속성에 추가해준 이유가 따로 있는지 궁금합니다

2024-02-05 02:31 UTC, kyeongjun-ko commented on src/utils/saveFigmaDataAsNestedStructure.js
> +    });
```
for (const key in node) {
    if (!excludedKeys.includes(key))
}
```
를 사용해서 iteration을 줄일수 있겠습니다.

2024-02-05 02:44 UTC, doitchuu commented on src/utils/saveFigmaDataAsNestedStructure.js
> +const PAGE_UNIT_DEPTH = 1;
`NODE`도 괜찮네요! 해당 부분도 통일성 있는 `NODE` 단어로 변경해두겠습니다 👍

2024-02-05 02:47 UTC, doitchuu commented on src/utils/saveFigmaDataAsNestedStructure.js
> +      "scrollBehavior",
내부에 있는 `excludedKeys`는 제외할 키들이라 제외했었습니다!

2024-02-05 02:48 UTC, doitchuu commented on src/utils/saveFigmaDataAsNestedStructure.js
> +    });
`for in` 문을 사용해서 재작성 해두겠습니다. 감사합니다 👍

2024-02-05 02:51 UTC, doitchuu commented on src/controllers/projectController.js
> +const saveFigmaDataAsNestedStructure = require("../utils/saveFigmaDataAsNestedStructure");
중첩된 구조로 피그마 Data를 재구조화 하는 함수라 네이밍이 많이 길긴 하네요 🥲
`saveNestedFigmaData`는 데이터를 바로 저장하는 느낌이라 한번 더 고민해보겠습니다 👍 
의견 감사합니다! :)

2024-02-05 03:07 UTC, tjd985 requested changes
추가 코멘트 작성했습니다!

2024-02-05 03:07 UTC, tjd985 commented on src/utils/saveFigmaDataAsNestedStructure.js
> +    });
```suggestion
  for (const key in node) {
    if (node.hasOwnProperty(key)) {
      if (!excludedKeys.includes(key)) {
        newNode.property[key] = node[key];
      }
    }
  }
```

이렇게 작성하면 시간복잡도를 줄일 수 있지 않을까요?

2024-02-05 03:09 UTC, doitchuu commented on src/utils/saveFigmaDataAsNestedStructure.js
> +    });
해당 로직으로 수정해두겠습니다. 감사합니다!

2024-02-05 07:57 UTC, kyeongjun-ko submitted a review, later dismissed
피드백 반영사항 확인했습니다.

2024-02-05 09:09 UTC, tjd985 requested changes
코멘트 확인 바랍니다!

2024-02-05 09:09 UTC, tjd985 commented on src/controllers/projectController.js
> +    const data = await responseJson.json();
- `P1`
`data`란 이름만 가지고는 해당 변수가 어떤것을 의미하는지 한눈에 파악하기 어려울 것 같습니다!

2024-02-05 09:09 UTC, tjd985 commented on src/loaders/errorHandler.js
> +};
- `P1`
저희 내부에서 정한 에러메세지 구조에 맞게 수정해주세요!

2024-02-05 09:18 UTC, kyeongjun-ko commented on src/loaders/index.js
> +  await errorLoader(app);
P5: 공통으로 사용할 수 있는 에러핸들러를 추가하셨군요 💯

2024-02-05 09:21 UTC, kyeongjun-ko commented on src/controllers/projectController.js
> +const ERROR_MESSAGE = require("../constants/error");
P4:
`ERROR_MESSAGE `보다 전체 에러 상태와 메세지를 포함하고 있는
객체이므로 `ERROR `라는 이름도 괜찮을것 같습니다.

2024-02-05 09:21 UTC, kyeongjun-ko commented on src/controllers/projectController.js
> +          Authorization: `Bearer ${accessToken}`,
P5: OAuth2.0 으로 받아온 사용자 토큰으로 API 요청시
헤더에 들어갈 속성과 값이 조금 달라지는 군요 👍

2024-02-05 09:21 UTC, tjd985 submitted a review, later dismissed
확인 완료했습니다
고생하셨습니다!

2024-02-05 09:21 UTC, tjd985 commented on src/loaders/error.js
> +};
반영해주셨군요!
감사합니다!!

2024-02-05 09:21 UTC, tjd985 commented on src/controllers/projectController.js
> +    const projectVersionSubtree = await responseJson.json();
변수명도 명시적으로 수정 되었네요! 💯

2024-02-05 09:21 UTC, tjd985 commented on src/controllers/projectController.js
> +    );
`http-error`를 사용해서 에러를 만들어 주셨군요!

2024-02-05 09:25 UTC, tjd985 approved these changes

2024-02-05 09:25 UTC, merged