Hotfix: 16MB 이상 피그마 파일 에러 해결을 위한 GridFS 를 활용한 로직 추가
Figci/Figci-Server pull request #31
Opened 2024-05-07 09:22 UTC by kyeongjun-ko

## Fix (이슈 번호)

none

<br />

## 해결하려던 문제를 알려주세요!

### 1. 16MB 이상 데이터 저장을 위해 몽고 DB  gridFS 기능을 활용한 저장 로직 추가.
### 2. 16MB 이상 gridFS 데이터 구조와 16MB 이하 MongoDB 데이터 구조 통일.
### 3. gridFS 데이터 `nodes` 값 데이터를 Map 구조로 변환시 캔버스 렌더링 에러 수정.
### 4. Page 선택 페이지, 비교 페이지 이동시 GridFS 파일 조회 로직 속도 개선.

<br />

## 어떻게 해결했나요?

### 1. 몽고 DB 16MB 이상 데이터 저장을 위해 gridFS 를 활용한 저장 로직 추가.
 - gridFS 파일 조회 로직과 저장 로직을 하나의 유틸 함수 `gridUtils.js` 에 추가. 
 - 몽고 DB bucket 재사용을 위해 `mongoose.js` 파일 `initBucket` 함수 추가.
 
### 2. 16MB 이상 gridFS 데이터 구조와 16MB 이하 데이터 구조 통일하기.
 - gridFS 조회시 `nodes` key 값의 데이터를 Map으로 변환시 FrameId 속성 소거.
 - 비교 로직 수행후 클라이언트에 전달시 'nodes' key 값의 데이터 타입 object로 변환.
 
### 3. gridFS 데이터 `nodes` 값 데이터를 Map 구조로 변환시 캔버스 렌더링 에러 수정.
 - 몽고 DB에서 조회한 document에서 메타데이터를 소거한 실제 데이터 조회를 위한 로직에서 에러 발생.
 - `_doc` 존재 하는지 조건을 추가함으로 gridFS 파일일 경우 분기 처리함.
 
### 4. Page 선택 페이지, 비교 페이지 이동시 GridFS 파일 조회 로직 속도 개선.
 - 새 Altas 몽고 DB 계정 추가  - 계정 Slack 팀 채널에 공유 `ID: figciAdmin / PW: ******** `
 - 팀원들 몽고 DB 사용자 권한 초대하기

<br />

## 잠깐! 확인해보셨나요?

- [x]  셀프 리뷰는 완료하셨나요?
- [x]  가장 최신 브랜치를 pull했나요?
- [x]  base 브랜치명을 확인하셨나요? (Front, Backend, feature 등)
- [x]  코드 컨벤션을 모두 지켰나요?
- [x]  적절한 라벨이 있나요?
- [x]  assignee가 있나요?

<br />

2024-05-10 14:44 UTC, doitchuu reviewed
리뷰 확인 부탁드립니다!

2024-05-10 14:44 UTC, doitchuu commented on src/constants/error.js
> +  },
커스텀 에러 처리로 해주셨네요 👍

2024-05-10 14:44 UTC, doitchuu commented on src/utils/getDocument.js
> +  }
여기도 `try catch`문이 있어야 하는 로직인가요?
궁금해서 질문 드립니다

2024-05-10 14:45 UTC, doitchuu commented on src/loaders/express.js
> +const expressLoader = async (app) => {
저희 컨벤션대로 함수 형태를 바꿔주셨네요 👍

2024-05-10 15:38 UTC, doitchuu requested changes
코멘트 확인 부탁드립니다 👍

2024-05-10 15:38 UTC, doitchuu commented on src/utils/convertObjectToMap.js
> +    return convertedObject;
P1: `return`위에 개행 부탁드려요!

```suggestion

    return convertedObject;
```

2024-05-10 15:38 UTC, doitchuu commented on src/utils/convertObjectToMap.js
> +  return gridFSObject;
P1: 여기도 동일하게 개행 부탁드려요!

2024-05-10 15:38 UTC, doitchuu commented on src/utils/getDocument.js
> +    );
요부분은 자동으로 띄어쓰기 되는 부분일까요..? 짧은데 되어있어서 궁금해서 질문드립니다 :)

2024-05-10 15:38 UTC, doitchuu commented on src/utils/gridfsUtils.js
> +module.exports = { getDocumentFromGridFS, saveDocumentToGridFS };
P2: 저희 기존 `util` 디렉토리에는 각 js파일 당 함수가 하나씩 들어가 있었는데
따로 함수를 분리해줘도 좋지 않을까요?

2024-05-10 15:43 UTC, doitchuu commented on src/utils/convertObjectToMap.js
> +    const convertedObject = {};
P1: 해당 부분도 개행 부탁드립니다.

```suggestion
    }
    
    const convertedObject = {};
```

2024-05-10 17:42 UTC, tjd985 requested changes
고생하셨습니다! 👍 
코멘트만 한번씩 확인 부탁드립니다

2024-05-10 17:42 UTC, tjd985 commented on src/controllers/projectController.js
> +    if (documentSize <= 16 * 1024 * 1024) {
- `P2`
해당 사이즈는 변하지 않는 값이니까 상수로 처리해두면 더 좋을 것 같습니다!

2024-05-10 17:42 UTC, tjd985 commented on src/loaders/express.js
> +const expressLoader = async (app) => {
컨벤션에 맞게 수정해주신 점 💯

2024-05-10 17:42 UTC, tjd985 commented on src/loaders/mongoose.js
> +  bucket = new GridFSBucket(db, { bucketName: CONSTANT.BUCKET_NAME });
- `P1`
선언부와 비즈니스 로직은 한줄 개행하는건 어떨까요!

```suggestion
  const db = mongoose.connection.client.db(CONFIG.DB_NAME);
  
  bucket = new GridFSBucket(db, { bucketName: CONSTANT.BUCKET_NAME });
```

2024-05-10 17:42 UTC, tjd985 commented on src/models/Document.js
> +  frameId: { type: String, require: true },
`nodes`에 `frameId`가 없는문제를 찾아서 해결해주셨네요^^ 👍

2024-05-10 17:42 UTC, tjd985 commented on src/utils/convertObjectToMap.js
> +};
- `P1`
`for...in`을 사용할때 `hasOwnProperty`를 같이 사용하면 좋을 것 같습니다!
추가적으로 컨벤션만 수정 부탁드립니다

```suggestion
const convertedObject = {};
const convertObjectToMap = (gridFSObject) => {
  if (gridFSObject && typeof gridFSObject === "object") {
    if (Array.isArray(gridFSObject)) {
      return gridFSObject.map(convertObjectToMap);
    }

    for (const key in gridFSObject) {
      if (key === "pages" || key === "frames" || key === "nodes") {
        const convertedMap = new Map();

        for (const [pageId, pageNodes] of Object.entries(gridFSObject[key])) {
          convertedMap.set(pageId, convertObjectToMap(pageNodes));
          convertedMap[pageId] = convertObjectToMap(pageNodes);
        }

        convertedObject[key] = convertedMap;
      } else {
        convertedObject[key] = convertObjectToMap(gridFSObject[key]);
      }
    }
    
    return convertedObject;
  }
  
  return gridFSObject;
};
```

2024-05-11 13:38 UTC, kyeongjun-ko commented on src/utils/gridfsUtils.js
> +module.exports = { getDocumentFromGridFS, saveDocumentToGridFS };
처음에는 각 함수별로 따로 파일로 분리하는것도 고려했었는데
`getDocumentFromGridFS` 와 `saveDocumentToGridFS` 모두 gridFS 라는 공통된 관심사에 관련된 함수이고
두 함수 모두 공동으로 사용하는`getBucket`라는 모듈이 존재하고 있고
`getDocumentFromGridFS` 함수를 `saveDocumentToGridFS` 에서 사용 하기때문에
두개의 파일을 각각 만들어서 require 하지 않고 하나의 파일에서 관리하는 방법을 선택했습니다.

2024-05-12 06:18 UTC, tjd985 approved these changes, later dismissed
확인했습니다!
고생하셨습니다 👍

2024-05-12 06:18 UTC, tjd985 commented on src/constants/constants.js
> +  MAX_DOCUMENT_SIZE: 16 * 1024 * 1024,
상수처리 굿! 👍

2024-05-12 06:18 UTC, tjd985 commented on src/utils/flattenFigmaSubtree.js
> +        if (isOwnProperty(node, key)) {
`isOwnProperty`로 수정해주셨네요 👍

2024-05-12 15:05 UTC, doitchuu commented on src/utils/gridfsUtils.js
> +module.exports = { getDocumentFromGridFS, saveDocumentToGridFS };
넵! 확인했습니다 👍

2024-05-13 02:40 UTC, kyeongjun-ko commented on src/utils/getDocument.js
> +  }
getDocument를 호출하는곳에서 에러핸들링을 하고있기때문에
내부 에러핸들링 로직은 삭제해도 괜찮을것 같습니다 👍

2024-05-13 02:40 UTC, doitchuu approved these changes
확인 완료했습니다 👍 
고생 하셨습니다!

2024-05-13 04:27 UTC, merged